name: update_playlist

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *' # প্রতি ৬ ঘণ্টা পর অটো রান হবে

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # পুরো হিস্ট্রি নিবে যাতে পুশ এরর না হয়

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: pip install aiohttp pyzipper

      - name: Run Fast Updater
        env:
          ZIP_PASSWORD: ${{ secrets.ZIP_PASSWORD }}
        run: python fast_updater.py

      - name: Commit and Push Changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git pull origin main # পুশ করার আগে লেটেস্ট কোড টেনে নিবে
          if [ -f playlist.m3u ]; then
            git add playlist.m3u
            git commit -m "Auto Update: $(date)" || echo "No changes to commit"
            git push origin main
          else
            echo "Error: playlist.m3u not found. Check if targets.txt exists!"
            exit 1
          fi
